id: A8E8EFB7E
title: f26AC
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:23:04.319681
  last_modified_at: 2022-05-27 19:23:04.319688
