id: A8E8EFB7E
title: fB03B
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:23:04.374926
  last_modified_at: 2022-05-27 19:23:04.374929
