id: A8E8EFB7E
title: f66EE
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:23:04.342429
  last_modified_at: 2022-05-27 19:23:04.342432
