id: A8E8EFB7E
title: f5F8F
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:23:04.339496
  last_modified_at: 2022-05-27 19:23:04.339501
