id: A8E8EFB7E
title: f763C
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 19:23:04.351977
  last_modified_at: 2022-05-27 19:23:04.351983
